### ISSUE TITLE
dateViewer shows up as 00 AM while using 12-hour time setting

### ISSUE THREAD

**Issue by kamekku14** [ezeholz/BDStuff#2]
I was expecting to see 12 AM in the midnight, but when I set to 12-hour time setting, this happened:
![image](https://user-images.githubusercontent.com/66167734/129392816-aec70f70-cec0-4f1d-b282-4cef9f0e378f.png)

**Comment by ezeholz** [comment]
Hey! I just see this issue. I'll add a fix in the next update.
I believe it's valid to use 12 or 00, so probably I'll use a toggle button in settings to change that.

**Comment by ezeholz** [comment]
I'm gonna close this issue now, because 1.11 most probably handle this problem.
Let me know if it isn't working. Cheers!
