### ISSUE TITLE
[dateViewer] breaking memberlist alignment after new update

### ISSUE THREAD

**Issue by gbslr** [ezeholz/BDStuff#3]
after the recent changes in v2.11, dateViewer now breaks the alignment of the memberlist and also does not display. unsure as to what might be causing this.

![image](https://user-images.githubusercontent.com/69027452/131770366-500cc6ab-bea9-47b6-8ddf-d233aea5f1e8.png)

**Comment by ezeholz** [comment]
Most probably it's giving an error, and it's showing in the upper right corner. Could you press CTRL + SHIFT + i and show me if it's any error there?

**Comment by gbslr** [comment]
Yep, I'm getting thrown this error on load. 

![image](https://user-images.githubusercontent.com/69027452/131812872-79ab6829-3d05-4fe6-85b1-f61fc57f2e62.png)

**Comment by ezeholz** [comment]
I see, I'll fix it ASAP. Thanks!

**Comment by ezeholz** [comment]
Please test the file in the `dev` branch. Let me know if it's working and if you're getting any warning in console.

**Comment by gbslr** [comment]
tested out the new build, seems to be working as intended. i think that most likely it wasn't handling a blank lang tag properly. thanks for fixing this so fast!

**Comment by ezeholz** [comment]
No problem! I'm gonna do a few changes and update the main version accordingly.
Thanks for letting me know that!
