### ISSUE TITLE
[dateViewer] Could not be compiled.

### ISSUE THREAD

**Issue by sadaakisz** [ezeholz/BDStuff#4]
Here is the error log when starting Discord and when re-adding the plugin:

![image](https://user-images.githubusercontent.com/40412908/133910960-c7bea25d-2991-46d6-92dd-12e0e43e8656.png)

And the console as requested:

![image](https://user-images.githubusercontent.com/40412908/133910970-ef0424a3-10fa-47e0-9ece-be02d5bfd5a5.png)

**Comment by ezeholz** [comment]
Hey! Try to download and install [this](https://raw.githubusercontent.com/ezeholz/BDStuff/main/Plugins/dateViewer/dateViewer.plugin.js) file. Open it and use right click, save as. Then drag the file inside your plugins folder.

**Comment by sadaakisz** [comment]
Thank you very much! Works like a charm now 🎉
